# Recipes for the action test framework.
# Import this module from the root Justfile with:
#   mod actions 'actions'
# Default to display help menu
default:
    @just --list --list-prefix '  actions::'
# Run all action tests
