# Recipes for the action test framework.
# Import this module from the root Justfile with:
#   mod actions 'actions'
# Default to display help menu
default:
    @just --list --list-prefix '  actions::'
# Run all action tests
test:
    cargo nextest run -p base-action-harness
# Run all action tests with the CI profile
test-ci:
    cargo nextest run -P ci --locked -p base-action-harness --cargo-profile ci
